//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button Project1Btn;
		
		protected System.Web.UI.WebControls.Panel panel;
		
		protected System.Web.UI.WebControls.TextBox EmailNameTextBox;
		
		protected System.Web.UI.WebControls.TextBox EmailTextBox;
		
		protected System.Web.UI.WebControls.TextBox EmailMessageTextBox;
		
		protected System.Web.UI.WebControls.Button SubmitBtn;
	}
}
